version: 2.1

orbs:
  nx: nrwl/nx@1.6.2

jobs:
  main:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout

      # Connect your workspace on staging.nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-jvm" --stop-agents-after="build"

      - nx/set-shas:
          main-branch-name: 'main'

      # Required for nx affected if we're on a branch
      - when:
          condition:
            matches: { pattern: "^pull/.*", value: << pipeline.git.branch >> }
          steps:
            - run: git branch --track main origin/main

      - run: ./nx affected --base=$NX_BASE --head=$NX_HEAD -t test build

workflows:
  version: 2

  ci:
    jobs:
      - main
